#taken from psycho with his agreement
[core]
name: devastatorHarpoon
class: CustomUnitMetadata
price: 2000
maxHp: 3000
mass: 9000
#armour: 5

#generation_resources:Power=-7
#generation_delay:100



#displayLocaleKey: antiAirTurret

#overrideAndReplace: turret
showInEditor:false

#footprint used for collisions with units (left, up, right, down)
footprint: -1,0,0,1

#used for placement, and placement of other buildings
constructionFootprint: -1,0,0,1

buildingToFootprintOffsetX:0
buildingToFootprintOffsetY:15


techLevel: 1
buildSpeed: 15s
#availableInDemo: true

radius: 16
#displayRadius: 25
buildingSelectionOffset: 0


isBuilding: true
isBio: false


[graphics]
total_frames: 1
frame_width: 100
frame_height: 100
drawLayer:ground2
image:        ROOT:data/null.png
image_wreak:  NONE
image_turret: NONE

icon_zoomed_out: NONE

teamColorsOnTurret: true
showShotDelayBar:false
scaleImagesTo: 24
#scaleTurretImagesTo: 9

#AUTO
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1




[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: if parent.hasFlag(id=14)
canAttackUnderwaterUnits: false
aimOffsetSpread: 0
turretSize: 12
turretTurnSpeed: 6
isFixedFiring:true
#canOnlyAttackUnitsWithoutTags: ApolloII, pcw, excelsior
maxAttackRange: 300
shootDelay: 5s


[turret_DummyHarpoon]
#Fake Turret only for visual
image:NONE
invisible:if self.isAttacking
x: 0
y: 12
attachedTo: Dummy
projectile: dummy
barrelX: 0
barrelY: 5
canShoot:false

[turret_Dummy]
#Fake Turret only for visual
x: 0
y: 0
idleDir:0
projectile: dummy
barrelX: 0
barrelY: 5

[turret_ChainDamage]
invisible:true
attachedTo: Dummy
slave: true
x: 0
y: 0
delay:3
projectile: ChainDamage
barrelX: 0
barrelY: 15
limitingMinRange: 100
canAttackCondition: if not self.hasFlag(id=30)
canOnlyAttackUnitsWithoutTags: ApolloII, pcw, excelsior, fatBoy
[turret_ChainDamage2]
invisible:true
attachedTo: Dummy
slave: true
x: 0
y: 0
delay:3
projectile: ChainDamage2
barrelX: 0
barrelY: 15
limitingMinRange: 150
canAttackCondition: if not self.hasFlag(id=30)
canOnlyAttackUnitsWithTags: ApolloII, pcw, excelsior, fatBoy
[turret_ChainEffect]
invisible:true
attachedTo: Dummy
slave: true
x: 0
y: -3
delay:0.05s
projectile: Chain
barrelX: 0
barrelY: 15
#shoot_sound:chains1.ogg
#shoot_sound_vol:0.05

[projectile_Chain]

image:Harpoon.png
directDamage: 0
life: 5
speed: 15
targetSpeed: 15
trailEffect: false
largeHitEffect: false
instant:true
delayedStartTimer:0.4s

frame: 4
deflectionPower: -1
autoTargetingOnDeadTarget: false
explodeEffect:NONE
beamImage:HarpoonChain.png
beamImageOffsetRate: -0.2
beamImageEnd:HarpoonPierced.png
shieldDamageMultiplier:0.50

[projectile_ChainDamage]
image:Harpoon.png
directDamage: 1
life: 100
speed: 21
targetSpeed: 21
trailEffect: false
largeHitEffect: false
instant:true
pushForce:-1500
pushVelocity:-0.5
frame: 1
deflectionPower: -1
autoTargetingOnDeadTarget: false
explodeEffect:NONE
[projectile_ChainDamage2]
@copyFromSection: projectile_ChainDamage
pushVelocity:-0.4

[projectile_dummy]
#Dummy Projectile
directDamage: 0
life: 0
speed: 0
instant: false
frame: 1
deflectionPower:-1
drawSize: 1
explodeEffect:NONE

[movement]
movementType: LAND
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 6
turnAcceleration: 0.5
